name: Run HIL Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  TIMEZONE: "Europe/Berlin"

jobs:
  test:
    runs-on: [rpi, cim, hil]

    # permissions:
    #   contents: read
    #   packages: write
    #   attestations: write
    #   id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: ${{ env.TIMEZONE }}
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y can-utils net-tools

      - name: Enable SPI and I^2C 
        run: |
          sudo raspi-config nonint do_spi 0
          sudo raspi-config nonint do_i2c 0

      # flash CIM firmware automatically
      # picotool

      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: true
          job-summary: true
          click-to-expand: false