name: Run HIL Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  TIMEZONE: "Europe/Berlin"

jobs:
  test:
    runs-on: [rpi, cim, hil]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: ${{ env.TIMEZONE }}

      - name: Enable SPI and I²C
        run: |
          sudo raspi-config nonint do_spi 0
          sudo raspi-config nonint do_i2c 0

      - name: Install uv if missing
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi

      - name: Run Tests with uv
        run: |
          uv run pytest -vv
